# POST http://localhost:5500/api/item
# Content-Type: application/json

# {
#     "item": "Fist to-Do List"
# }

GET http://localhost:5500/api/items
Content-Type: application/json

# PUT http://localhost:5500/api/item/63d2220b044ab14cd5df85d8
# Content-Type: application/json

# {
#     "item": "Fist updated to-Do List"
# }


# DELETE  http://localhost:5500/api/item/63d110651803a20da91be599
# Content-Type: application/json